//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.18 at 10:01:58 PM EST 
//


package org.mobicents.gmlc.slee.mlp.v3_4;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{<a href="http://www.w3.org/2001/XMLSchema">...</a>}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}target_area"/>
 *         &lt;element ref="{}no_of_reports" minOccurs="0"/>
 *         &lt;element ref="{}minimumIntervalTime" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="type" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *             &lt;enumeration value="MS_ENTERING"/>
 *             &lt;enumeration value="MS_LEAVING"/>
 *             &lt;enumeration value="MS_WITHIN_AREA"/>
 *             &lt;enumeration value="MS_OUTSIDE_AREA"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="loc_estimates" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *             &lt;enumeration value="TRUE"/>
 *             &lt;enumeration value="FALSE"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "targetArea",
    "noOfReports",
    "minimumIntervalTime"
})
@XmlRootElement(name = "change_area")
public class ChangeArea {

    @XmlElement(name = "target_area", required = true)
    protected TargetArea targetArea;
    @XmlElement(name = "no_of_reports")
    protected String noOfReports;
    protected String minimumIntervalTime;
    @XmlAttribute(name = "type", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String type;
    @XmlAttribute(name = "loc_estimates", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String locEstimates;

    /**
     * Gets the value of the targetArea property.
     * 
     * @return
     *     possible object is
     *     {@link TargetArea }
     *     
     */
    public TargetArea getTargetArea() {
        return targetArea;
    }

    /**
     * Sets the value of the targetArea property.
     * 
     * @param value
     *     allowed object is
     *     {@link TargetArea }
     *     
     */
    public void setTargetArea(TargetArea value) {
        this.targetArea = value;
    }

    /**
     * Gets the value of the noOfReports property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNoOfReports() {
        return noOfReports;
    }

    /**
     * Sets the value of the noOfReports property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNoOfReports(String value) {
        this.noOfReports = value;
    }

    /**
     * Gets the value of the minimumIntervalTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMinimumIntervalTime() {
        return minimumIntervalTime;
    }

    /**
     * Sets the value of the minimumIntervalTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMinimumIntervalTime(String value) {
        this.minimumIntervalTime = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the locEstimates property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocEstimates() {
        return locEstimates;
    }

    /**
     * Sets the value of the locEstimates property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocEstimates(String value) {
        this.locEstimates = value;
    }

}
