//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.18 at 10:01:58 PM EST 
//


package org.mobicents.gmlc.slee.mlp.v3_4;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{<a href="http://www.w3.org/2001/XMLSchema">...</a>}anyType">
 *       &lt;attribute name="element_type" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *             &lt;enumeration value="COUNTRY"/>
 *             &lt;enumeration value="A1"/>
 *             &lt;enumeration value="A2"/>
 *             &lt;enumeration value="A3"/>
 *             &lt;enumeration value="A4"/>
 *             &lt;enumeration value="A5"/>
 *             &lt;enumeration value="A6"/>
 *             &lt;enumeration value="PRD"/>
 *             &lt;enumeration value="POD"/>
 *             &lt;enumeration value="STS"/>
 *             &lt;enumeration value="HNO"/>
 *             &lt;enumeration value="HNS"/>
 *             &lt;enumeration value="LMK"/>
 *             &lt;enumeration value="LOC"/>
 *             &lt;enumeration value="FLR"/>
 *             &lt;enumeration value="NAM"/>
 *             &lt;enumeration value="PC"/>
 *             &lt;enumeration value="BLD"/>
 *             &lt;enumeration value="UNIT"/>
 *             &lt;enumeration value="ROOM"/>
 *             &lt;enumeration value="PLC"/>
 *             &lt;enumeration value="PCN"/>
 *             &lt;enumeration value="POBOX"/>
 *             &lt;enumeration value="ADDCODE"/>
 *             &lt;enumeration value="SEAT"/>
 *             &lt;enumeration value="RD"/>
 *             &lt;enumeration value="RDSEC"/>
 *             &lt;enumeration value="RDBR"/>
 *             &lt;enumeration value="RDSUBBR"/>
 *             &lt;enumeration value="PRM"/>
 *             &lt;enumeration value="POM"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute ref="{http://www.w3.org/XML/1998/namespace}lang"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "content"
})
@XmlRootElement(name = "civicloc_element")
public class CiviclocElement {

    @XmlValue
    protected String content;
    @XmlAttribute(name = "element_type", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String elementType;
    @XmlAttribute(name = "lang", namespace = "http://www.w3.org/XML/1998/namespace")
    protected String lang;

    /**
     * Gets the value of the content property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContent() {
        return content;
    }

    /**
     * Sets the value of the content property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContent(String value) {
        this.content = value;
    }

    /**
     * Gets the value of the elementType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getElementType() {
        return elementType;
    }

    /**
     * Sets the value of the elementType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setElementType(String value) {
        this.elementType = value;
    }

    /**
     * Gets the value of the lang property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLang() {
        return lang;
    }

    /**
     * Sets the value of the lang property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLang(String value) {
        this.lang = value;
    }

}
