//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.18 at 10:01:58 PM EST 
//


package org.mobicents.gmlc.slee.mlp.v3_4;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{<a href="http://www.w3.org/2001/XMLSchema">...</a>}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}time"/>
 *         &lt;choice>
 *           &lt;element ref="{}shape"/>
 *           &lt;element ref="{}civicloc"/>
 *         &lt;/choice>
 *         &lt;element ref="{}MapData" minOccurs="0"/>
 *         &lt;sequence minOccurs="0">
 *           &lt;element ref="{}alt"/>
 *           &lt;element ref="{}alt_unc" minOccurs="0"/>
 *         &lt;/sequence>
 *         &lt;element ref="{}speed" minOccurs="0"/>
 *         &lt;element ref="{}direction" minOccurs="0"/>
 *         &lt;element ref="{}lev_conf" minOccurs="0"/>
 *         &lt;element ref="{}qos_not_met" minOccurs="0"/>
 *         &lt;element ref="{}MotionStateList" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "time",
    "shape",
    "civicloc",
    "mapData",
    "alt",
    "altUnc",
    "speed",
    "direction",
    "levConf",
    "qosNotMet",
    "motionStateList"
})
@XmlRootElement(name = "pd")
public class Pd {

    @XmlElement(required = true)
    protected Time time;
    protected Shape shape;
    protected Civicloc civicloc;
    @XmlElement(name = "MapData")
    protected MapData mapData;
    protected String alt;
    @XmlElement(name = "alt_unc")
    protected String altUnc;
    protected String speed;
    protected String direction;
    @XmlElement(name = "lev_conf")
    protected String levConf;
    @XmlElement(name = "qos_not_met")
    protected QosNotMet qosNotMet;
    @XmlElement(name = "MotionStateList")
    protected MotionStateList motionStateList;

    /**
     * Gets the value of the time property.
     * 
     * @return
     *     possible object is
     *     {@link Time }
     *     
     */
    public Time getTime() {
        return time;
    }

    /**
     * Sets the value of the time property.
     * 
     * @param value
     *     allowed object is
     *     {@link Time }
     *     
     */
    public void setTime(Time value) {
        this.time = value;
    }

    /**
     * Gets the value of the shape property.
     * 
     * @return
     *     possible object is
     *     {@link Shape }
     *     
     */
    public Shape getShape() {
        return shape;
    }

    /**
     * Sets the value of the shape property.
     * 
     * @param value
     *     allowed object is
     *     {@link Shape }
     *     
     */
    public void setShape(Shape value) {
        this.shape = value;
    }

    /**
     * Gets the value of the civicloc property.
     * 
     * @return
     *     possible object is
     *     {@link Civicloc }
     *     
     */
    public Civicloc getCivicloc() {
        return civicloc;
    }

    /**
     * Sets the value of the civicloc property.
     * 
     * @param value
     *     allowed object is
     *     {@link Civicloc }
     *     
     */
    public void setCivicloc(Civicloc value) {
        this.civicloc = value;
    }

    /**
     * Gets the value of the mapData property.
     * 
     * @return
     *     possible object is
     *     {@link MapData }
     *     
     */
    public MapData getMapData() {
        return mapData;
    }

    /**
     * Sets the value of the mapData property.
     * 
     * @param value
     *     allowed object is
     *     {@link MapData }
     *     
     */
    public void setMapData(MapData value) {
        this.mapData = value;
    }

    /**
     * Gets the value of the alt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAlt() {
        return alt;
    }

    /**
     * Sets the value of the alt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAlt(String value) {
        this.alt = value;
    }

    /**
     * Gets the value of the altUnc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAltUnc() {
        return altUnc;
    }

    /**
     * Sets the value of the altUnc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAltUnc(String value) {
        this.altUnc = value;
    }

    /**
     * Gets the value of the speed property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpeed() {
        return speed;
    }

    /**
     * Sets the value of the speed property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpeed(String value) {
        this.speed = value;
    }

    /**
     * Gets the value of the direction property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDirection() {
        return direction;
    }

    /**
     * Sets the value of the direction property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDirection(String value) {
        this.direction = value;
    }

    /**
     * Gets the value of the levConf property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLevConf() {
        return levConf;
    }

    /**
     * Sets the value of the levConf property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLevConf(String value) {
        this.levConf = value;
    }

    /**
     * Gets the value of the qosNotMet property.
     * 
     * @return
     *     possible object is
     *     {@link QosNotMet }
     *     
     */
    public QosNotMet getQosNotMet() {
        return qosNotMet;
    }

    /**
     * Sets the value of the qosNotMet property.
     * 
     * @param value
     *     allowed object is
     *     {@link QosNotMet }
     *     
     */
    public void setQosNotMet(QosNotMet value) {
        this.qosNotMet = value;
    }

    /**
     * Gets the value of the motionStateList property.
     * 
     * @return
     *     possible object is
     *     {@link MotionStateList }
     *     
     */
    public MotionStateList getMotionStateList() {
        return motionStateList;
    }

    /**
     * Sets the value of the motionStateList property.
     * 
     * @param value
     *     allowed object is
     *     {@link MotionStateList }
     *     
     */
    public void setMotionStateList(MotionStateList value) {
        this.motionStateList = value;
    }

}
