//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.18 at 10:01:58 PM EST 
//


package org.mobicents.gmlc.slee.mlp.v3_4;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{<a href="http://www.w3.org/2001/XMLSchema">...</a>}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}mcc"/>
 *         &lt;element ref="{}mnc"/>
 *         &lt;element ref="{}lac"/>
 *         &lt;element ref="{}sac"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "mcc",
    "mnc",
    "lac",
    "sac"
})
@XmlRootElement(name = "sai")
public class Sai {

    @XmlElement(required = true)
    protected String mcc;
    @XmlElement(required = true)
    protected String mnc;
    @XmlElement(required = true)
    protected String lac;
    @XmlElement(required = true)
    protected String sac;

    /**
     * Gets the value of the mcc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMcc() {
        return mcc;
    }

    /**
     * Sets the value of the mcc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMcc(String value) {
        this.mcc = value;
    }

    /**
     * Gets the value of the mnc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMnc() {
        return mnc;
    }

    /**
     * Sets the value of the mnc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMnc(String value) {
        this.mnc = value;
    }

    /**
     * Gets the value of the lac property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLac() {
        return lac;
    }

    /**
     * Sets the value of the lac property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLac(String value) {
        this.lac = value;
    }

    /**
     * Gets the value of the sac property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSac() {
        return sac;
    }

    /**
     * Sets the value of the sac property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSac(String value) {
        this.sac = value;
    }

}
