//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.18 at 10:01:58 PM EST 
//


package org.mobicents.gmlc.slee.mlp.v3_4;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{<a href="http://www.w3.org/2001/XMLSchema">...</a>}anyType">
 *       &lt;choice>
 *         &lt;element ref="{}cgi"/>
 *         &lt;element ref="{}sai"/>
 *         &lt;sequence>
 *           &lt;element ref="{}mcc"/>
 *           &lt;element ref="{}mnc"/>
 *           &lt;element ref="{}lte_ci"/>
 *         &lt;/sequence>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "cgi",
    "sai",
    "mcc",
    "mnc",
    "lteCi"
})
@XmlRootElement(name = "serving_cell")
public class ServingCell {

    protected Cgi cgi;
    protected Sai sai;
    protected String mcc;
    protected String mnc;
    @XmlElement(name = "lte_ci")
    protected String lteCi;

    /**
     * Gets the value of the cgi property.
     *
     * @return
     *     possible object is
     *     {@link Cgi }
     *
     */
    public Cgi getCgi() {
        return cgi;
    }

    /**
     * Sets the value of the cgi property.
     *
     * @param value
     *     allowed object is
     *     {@link Cgi }
     *
     */
    public void setCgi(Cgi value) {
        this.cgi = value;
    }

    /**
     * Gets the value of the sai property.
     *
     * @return
     *     possible object is
     *     {@link Sai }
     *
     */
    public Sai getSai() {
        return sai;
    }

    /**
     * Sets the value of the sai property.
     *
     * @param value
     *     allowed object is
     *     {@link Sai }
     *
     */
    public void setSai(Sai value) {
        this.sai = value;
    }

    /**
     * Gets the value of the mcc property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getMcc() {
        return mcc;
    }

    /**
     * Sets the value of the mcc property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setMcc(String value) {
        this.mcc = value;
    }

    /**
     * Gets the value of the mnc property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getMnc() {
        return mnc;
    }

    /**
     * Sets the value of the mnc property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setMnc(String value) {
        this.mnc = value;
    }

    /**
     * Gets the value of the lteCi property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getLteCi() {
        return lteCi;
    }

    /**
     * Sets the value of the lteCi property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setLteCi(String value) {
        this.lteCi = value;
    }

}
