//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.18 at 10:01:58 PM EST 
//


package org.mobicents.gmlc.slee.mlp.v3_4;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{<a href="http://www.w3.org/2001/XMLSchema">...</a>}anyType">
 *       &lt;choice>
 *         &lt;sequence>
 *           &lt;element ref="{}req_id"/>
 *           &lt;element ref="{}lcs_ref" minOccurs="0"/>
 *         &lt;/sequence>
 *         &lt;sequence>
 *           &lt;element ref="{}result"/>
 *           &lt;element ref="{}add_info" minOccurs="0"/>
 *         &lt;/sequence>
 *       &lt;/choice>
 *       &lt;attribute name="ver" default="3.4.0">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="3.4.0"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "reqId",
    "lcsRef",
    "result",
    "addInfo",
    "extensionParams"
})
@XmlRootElement(name = "tlra")
public class Tlra {

    @XmlElement(name = "req_id")
    protected String reqId;
    @XmlElement(name = "lcs_ref")
    protected String lcsRef;
    protected Result result;
    @XmlElement(name = "add_info")
    protected String addInfo;
    @XmlAttribute(name = "ver")
    protected String ver;
    @XmlElementRef(name = "extension_params", type = ExtensionParams.class, required = false)
    protected ExtensionParams extensionParams;

    /**
     * Gets the value of the reqId property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getReqId() {
        return reqId;
    }

    /**
     * Sets the value of the reqId property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setReqId(String value) {
        this.reqId = value;
    }

    /**
     * Gets the value of the lcsRef property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getLcsRef() {
        return lcsRef;
    }

    /**
     * Sets the value of the lcsRef property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setLcsRef(String value) {
        this.lcsRef = value;
    }

    /**
     * Gets the value of the result property.
     *
     * @return
     *     possible object is
     *     {@link Result }
     *
     */
    public Result getResult() {
        return result;
    }

    /**
     * Sets the value of the result property.
     *
     * @param value
     *     allowed object is
     *     {@link Result }
     *
     */
    public void setResult(Result value) {
        this.result = value;
    }

    /**
     * Gets the value of the addInfo property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getAddInfo() {
        return addInfo;
    }

    /**
     * Sets the value of the addInfo property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setAddInfo(String value) {
        this.addInfo = value;
    }

    /**
     * Gets the value of the ver property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getVer() {
        if (ver == null) {
            return "3.4.0";
        } else {
            return ver;
        }
    }

    /**
     * Sets the value of the ver property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setVer(String value) {
        this.ver = value;
    }

    /**
     * Gets the value of the extensionParams property.
     *
     * @return
     *     possible object is
     *     {@link ExtensionParams }
     *
     */
    public ExtensionParams getExtensionParams() {
        return extensionParams;
    }

    /**
     * Sets the value of the extensionParams property.
     *
     * @param value
     *     allowed object is
     *     {@link ExtensionParams }
     *
     */
    public void setExtensionParams(ExtensionParams value) {
        this.extensionParams = value;
    }
}
