//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.18 at 10:01:58 PM EST 
//


package org.mobicents.gmlc.slee.mlp.v3_4;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{<a href="http://www.w3.org/2001/XMLSchema">...</a>}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}req_id"/>
 *         &lt;element ref="{}lcs_ref" minOccurs="0"/>
 *         &lt;element ref="{}trl_pos" maxOccurs="unbounded"/>
 *         &lt;element ref="{}time_remaining" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="ver" default="3.4.0">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="3.4.0"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="more" default="NO">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *             &lt;enumeration value="YES"/>
 *             &lt;enumeration value="NO"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "reqId",
    "lcsRef",
    "trlPos",
    "timeRemaining",
    "extensionParams"
})
@XmlRootElement(name = "tlrep")
public class Tlrep {

    @XmlElement(name = "req_id", required = true)
    protected String reqId;
    @XmlElement(name = "lcs_ref")
    protected String lcsRef;
    @XmlElement(name = "trl_pos", required = true)
    protected List<TrlPos> trlPos;
    @XmlElement(name = "time_remaining")
    protected String timeRemaining;
    @XmlAttribute(name = "ver")
    protected String ver;
    @XmlAttribute(name = "more")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String more;
    @XmlElementRef(name = "extension_params", type = ExtensionParams.class, required = false)
    protected ExtensionParams extensionParams;

    /**
     * Gets the value of the reqId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReqId() {
        return reqId;
    }

    /**
     * Sets the value of the reqId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReqId(String value) {
        this.reqId = value;
    }

    /**
     * Gets the value of the lcsRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLcsRef() {
        return lcsRef;
    }

    /**
     * Sets the value of the lcsRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLcsRef(String value) {
        this.lcsRef = value;
    }

    /**
     * Gets the value of the trlPos property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the trlPos property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTrlPos().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TrlPos }
     * 
     * 
     */
    public List<TrlPos> getTrlPos() {
        if (trlPos == null) {
            trlPos = new ArrayList<>();
        }
        return this.trlPos;
    }

    /**
     * Gets the value of the timeRemaining property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTimeRemaining() {
        return timeRemaining;
    }

    /**
     * Sets the value of the timeRemaining property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTimeRemaining(String value) {
        this.timeRemaining = value;
    }

    /**
     * Gets the value of the ver property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVer() {
        if (ver == null) {
            return "3.4.0";
        } else {
            return ver;
        }
    }

    /**
     * Sets the value of the ver property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVer(String value) {
        this.ver = value;
    }

    /**
     * Gets the value of the more property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMore() {
        if (more == null) {
            return "NO";
        } else {
            return more;
        }
    }

    /**
     * Sets the value of the more property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMore(String value) {
        this.more = value;
    }

    /**
     * Gets the value of the extensionParams property.
     *
     * @return
     *     possible object is
     *     {@link ExtensionParams }
     *
     */
    public ExtensionParams getExtensionParams() {
        return extensionParams;
    }

    /**
     * Sets the value of the extensionParams property.
     *
     * @param value
     *     allowed object is
     *     {@link ExtensionParams }
     *
     */
    public void setExtensionParams(ExtensionParams value) {
        this.extensionParams = value;
    }
}
