//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.18 at 10:01:58 PM EST 
//


package org.mobicents.gmlc.slee.mlp.v3_4;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{<a href="http://www.w3.org/2001/XMLSchema">...</a>}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}msid"/>
 *         &lt;element ref="{}reference_object" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;choice>
 *           &lt;element ref="{}pd"/>
 *           &lt;element ref="{}poserr"/>
 *           &lt;element ref="{}time"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *       &lt;attribute name="trl_trigger" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *             &lt;enumeration value="PERIODIC"/>
 *             &lt;enumeration value="MS_AVAIL"/>
 *             &lt;enumeration value="CHANGE_AREA"/>
 *             &lt;enumeration value="VELOCITY"/>
 *             &lt;enumeration value="DISTANCE"/>
 *             &lt;enumeration value="EQUIDISTANCE"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="pos_method">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *             &lt;enumeration value="CELL"/>
 *             &lt;enumeration value="OTDOA"/>
 *             &lt;enumeration value="GPS"/>
 *             &lt;enumeration value="A-GPS"/>
 *             &lt;enumeration value="GNSS"/>
 *             &lt;enumeration value="A-GNSS"/>
 *             &lt;enumeration value="E-OTD"/>
 *             &lt;enumeration value="U-TDOA"/>
 *             &lt;enumeration value="AFLT"/>
 *             &lt;enumeration value="EFLT"/>
 *             &lt;enumeration value="E-CID"/>
 *             &lt;enumeration value="UNKNOWN"/>
 *             &lt;enumeration value="OTHER"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "msid",
    "referenceObject",
    "pd",
    "poserr",
    "time"
})
@XmlRootElement(name = "trl_pos")
public class TrlPos {

    @XmlElement(required = true)
    protected Msid msid;
    @XmlElement(name = "reference_object")
    protected List<ReferenceObject> referenceObject;
    protected Pd pd;
    protected Poserr poserr;
    protected Time time;
    @XmlAttribute(name = "trl_trigger", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String trlTrigger;
    @XmlAttribute(name = "pos_method")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String posMethod;

    /**
     * Gets the value of the msid property.
     *
     * @return
     *     possible object is
     *     {@link Msid }
     *
     */
    public Msid getMsid() {
        return msid;
    }

    /**
     * Sets the value of the msid property.
     *
     * @param value
     *     allowed object is
     *     {@link Msid }
     *
     */
    public void setMsid(Msid value) {
        this.msid = value;
    }

    /**
     * Gets the value of the referenceObject property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the referenceObject property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getReferenceObject().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ReferenceObject }
     *
     *
     */
    public List<ReferenceObject> getReferenceObject() {
        if (referenceObject == null) {
            referenceObject = new ArrayList<>();
        }
        return this.referenceObject;
    }

    /**
     * Gets the value of the pd property.
     *
     * @return
     *     possible object is
     *     {@link Pd }
     *
     */
    public Pd getPd() {
        return pd;
    }

    /**
     * Sets the value of the pd property.
     *
     * @param value
     *     allowed object is
     *     {@link Pd }
     *
     */
    public void setPd(Pd value) {
        this.pd = value;
    }

    /**
     * Gets the value of the poserr property.
     *
     * @return
     *     possible object is
     *     {@link Poserr }
     *
     */
    public Poserr getPoserr() {
        return poserr;
    }

    /**
     * Sets the value of the poserr property.
     *
     * @param value
     *     allowed object is
     *     {@link Poserr }
     *
     */
    public void setPoserr(Poserr value) {
        this.poserr = value;
    }

    /**
     * Gets the value of the time property.
     *
     * @return
     *     possible object is
     *     {@link Time }
     *
     */
    public Time getTime() {
        return time;
    }

    /**
     * Sets the value of the time property.
     *
     * @param value
     *     allowed object is
     *     {@link Time }
     *
     */
    public void setTime(Time value) {
        this.time = value;
    }

    /**
     * Gets the value of the trlTrigger property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getTrlTrigger() {
        return trlTrigger;
    }

    /**
     * Sets the value of the trlTrigger property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setTrlTrigger(String value) {
        this.trlTrigger = value;
    }

    /**
     * Gets the value of the posMethod property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getPosMethod() {
        return posMethod;
    }

    /**
     * Sets the value of the posMethod property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setPosMethod(String value) {
        this.posMethod = value;
    }
}
